Fix (upstream) crash for protected access settings
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:10)
	at im.vector.app.features.settings.VectorSettingsPinFragment.refreshPinCodeStatus(VectorSettingsPinFragment.kt:1)
	at im.vector.app.features.settings.VectorSettingsPinFragment.bindPref(VectorSettingsPinFragment.kt:1)
	at im.vector.app.features.settings.VectorSettingsBaseFragment.onCreatePreferences(VectorSettingsBaseFragment.kt:8)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:74)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:22)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:52)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:149)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1135)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:82)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:74)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

Change-Id: Iac3e08d95338417f69ee71ce0b185b825b9b0333